// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Mixvault_API.Models;

#nullable disable

namespace Mixvault_API.Migrations
{
    [DbContext(typeof(MixVault))]
    partial class MixVaultModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseCollation("utf8mb4_0900_ai_ci")
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.HasCharSet(modelBuilder, "utf8mb4");

            modelBuilder.Entity("Mixvault_API.Models.Playlist", b =>
                {
                    b.Property<int>("PlaylistId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("PlaylistID");

                    b.Property<int>("FkUser")
                        .HasColumnType("int")
                        .HasColumnName("fkUser");

                    b.Property<string>("PlaylistArtworkUrl")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("PlaylistArtworkURL");

                    b.Property<DateTime?>("PlaylistCreatedAt")
                        .HasColumnType("datetime");

                    b.Property<string>("PlaylistDescription")
                        .HasColumnType("mediumtext");

                    b.Property<string>("PlaylistGenre")
                        .HasColumnType("mediumtext");

                    b.Property<string>("PlaylistName")
                        .HasColumnType("mediumtext");

                    b.Property<string>("PlaylistTags")
                        .HasColumnType("mediumtext");

                    b.HasKey("PlaylistId")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "FkUser" }, "fkUser");

                    b.ToTable("playlist", (string)null);
                });

            modelBuilder.Entity("Mixvault_API.Models.Playlisthastrack", b =>
                {
                    b.Property<int>("PlaylistHasTracksId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("PlaylistHasTracksID");

                    b.Property<int>("FkPlaylist")
                        .HasColumnType("int")
                        .HasColumnName("fkPlaylist");

                    b.Property<int>("FkTrack")
                        .HasColumnType("int")
                        .HasColumnName("fkTrack");

                    b.Property<int>("Position")
                        .HasColumnType("int");

                    b.HasKey("PlaylistHasTracksId")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "FkPlaylist" }, "fkPlaylist");

                    b.HasIndex(new[] { "FkTrack" }, "fkTrack");

                    b.ToTable("playlisthastracks", (string)null);
                });

            modelBuilder.Entity("Mixvault_API.Models.Track", b =>
                {
                    b.Property<int>("TrackId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("TrackID");

                    b.Property<double?>("DurationMs")
                        .HasColumnType("double");

                    b.Property<int>("FkUser")
                        .HasColumnType("int")
                        .HasColumnName("fkUser");

                    b.Property<string>("Title")
                        .HasColumnType("mediumtext");

                    b.Property<string>("TrackArtist")
                        .HasColumnType("longtext");

                    b.Property<string>("TrackArtworkUrl")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("TrackArtworkURL");

                    b.Property<string>("TrackFileUrl")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("TrackFileURL");

                    b.Property<string>("TrackGenre")
                        .HasColumnType("mediumtext");

                    b.Property<string>("TrackTags")
                        .HasColumnType("mediumtext");

                    b.Property<DateTime?>("TrackUploadedAt")
                        .HasColumnType("datetime");

                    b.HasKey("TrackId")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "FkUser" }, "fkUser")
                        .HasDatabaseName("fkUser1");

                    b.ToTable("track", (string)null);
                });

            modelBuilder.Entity("Mixvault_API.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("UserID");

                    b.Property<string>("DisplayName")
                        .HasColumnType("mediumtext");

                    b.Property<string>("Email")
                        .HasColumnType("mediumtext");

                    b.Property<string>("Password")
                        .HasColumnType("mediumtext");

                    b.Property<string>("ProfilePictureUrl")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("ProfilePictureURL");

                    b.Property<DateTime?>("UserCreatedAt")
                        .HasColumnType("datetime");

                    b.HasKey("UserId")
                        .HasName("PRIMARY");

                    b.ToTable("user", (string)null);
                });

            modelBuilder.Entity("Mixvault_API.Models.Userlikesplaylist", b =>
                {
                    b.Property<int>("UserLikesPlaylistId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("UserLikesPlaylistID");

                    b.Property<int>("FkPlaylist")
                        .HasColumnType("int")
                        .HasColumnName("fkPlaylist");

                    b.Property<int>("FkUser")
                        .HasColumnType("int")
                        .HasColumnName("fkUser");

                    b.HasKey("UserLikesPlaylistId")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "FkPlaylist" }, "fkPlaylist")
                        .HasDatabaseName("fkPlaylist1");

                    b.HasIndex(new[] { "FkUser" }, "fkUser")
                        .HasDatabaseName("fkUser2");

                    b.ToTable("userlikesplaylist", (string)null);
                });

            modelBuilder.Entity("Mixvault_API.Models.Userlikestrack", b =>
                {
                    b.Property<int>("UserLikesTrackId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("UserLikesTrackID");

                    b.Property<int>("FkTrack")
                        .HasColumnType("int")
                        .HasColumnName("fkTrack");

                    b.Property<int>("FkUser")
                        .HasColumnType("int")
                        .HasColumnName("fkUser");

                    b.HasKey("UserLikesTrackId")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "FkTrack" }, "fkTrack")
                        .HasDatabaseName("fkTrack1");

                    b.HasIndex(new[] { "FkUser" }, "fkUser")
                        .HasDatabaseName("fkUser3");

                    b.ToTable("userlikestrack", (string)null);
                });

            modelBuilder.Entity("Mixvault_API.Models.Playlist", b =>
                {
                    b.HasOne("Mixvault_API.Models.User", "FkUserNavigation")
                        .WithMany("Playlists")
                        .HasForeignKey("FkUser")
                        .IsRequired()
                        .HasConstraintName("playlist_ibfk_1");

                    b.Navigation("FkUserNavigation");
                });

            modelBuilder.Entity("Mixvault_API.Models.Playlisthastrack", b =>
                {
                    b.HasOne("Mixvault_API.Models.Playlist", "FkPlaylistNavigation")
                        .WithMany("Playlisthastracks")
                        .HasForeignKey("FkPlaylist")
                        .IsRequired()
                        .HasConstraintName("playlisthastracks_ibfk_2");

                    b.HasOne("Mixvault_API.Models.Track", "FkTrackNavigation")
                        .WithMany("Playlisthastracks")
                        .HasForeignKey("FkTrack")
                        .IsRequired()
                        .HasConstraintName("playlisthastracks_ibfk_1");

                    b.Navigation("FkPlaylistNavigation");

                    b.Navigation("FkTrackNavigation");
                });

            modelBuilder.Entity("Mixvault_API.Models.Track", b =>
                {
                    b.HasOne("Mixvault_API.Models.User", "FkUserNavigation")
                        .WithMany("Tracks")
                        .HasForeignKey("FkUser")
                        .IsRequired()
                        .HasConstraintName("track_ibfk_1");

                    b.Navigation("FkUserNavigation");
                });

            modelBuilder.Entity("Mixvault_API.Models.Userlikesplaylist", b =>
                {
                    b.HasOne("Mixvault_API.Models.Playlist", "FkPlaylistNavigation")
                        .WithMany("Userlikesplaylists")
                        .HasForeignKey("FkPlaylist")
                        .IsRequired()
                        .HasConstraintName("userlikesplaylist_ibfk_2");

                    b.HasOne("Mixvault_API.Models.User", "FkUserNavigation")
                        .WithMany("Userlikesplaylists")
                        .HasForeignKey("FkUser")
                        .IsRequired()
                        .HasConstraintName("userlikesplaylist_ibfk_1");

                    b.Navigation("FkPlaylistNavigation");

                    b.Navigation("FkUserNavigation");
                });

            modelBuilder.Entity("Mixvault_API.Models.Userlikestrack", b =>
                {
                    b.HasOne("Mixvault_API.Models.Track", "FkTrackNavigation")
                        .WithMany("Userlikestracks")
                        .HasForeignKey("FkTrack")
                        .IsRequired()
                        .HasConstraintName("userlikestrack_ibfk_2");

                    b.HasOne("Mixvault_API.Models.User", "FkUserNavigation")
                        .WithMany("Userlikestracks")
                        .HasForeignKey("FkUser")
                        .IsRequired()
                        .HasConstraintName("userlikestrack_ibfk_1");

                    b.Navigation("FkTrackNavigation");

                    b.Navigation("FkUserNavigation");
                });

            modelBuilder.Entity("Mixvault_API.Models.Playlist", b =>
                {
                    b.Navigation("Playlisthastracks");

                    b.Navigation("Userlikesplaylists");
                });

            modelBuilder.Entity("Mixvault_API.Models.Track", b =>
                {
                    b.Navigation("Playlisthastracks");

                    b.Navigation("Userlikestracks");
                });

            modelBuilder.Entity("Mixvault_API.Models.User", b =>
                {
                    b.Navigation("Playlists");

                    b.Navigation("Tracks");

                    b.Navigation("Userlikesplaylists");

                    b.Navigation("Userlikestracks");
                });
#pragma warning restore 612, 618
        }
    }
}
